# inventory.yml
all:
  children:
    fastapi:
      hosts:
        fastapi:
          ansible_host: 3.141.47.167
          ansible_user: ec2-user
    postgres:
      hosts:
        postgres:
          ansible_host: 10.0.24.153
          ansible_user: ec2-user
          ansible_ssh_common_args: '-o ProxyCommand="ssh -W %h:%p -q ec2-user@3.141.47.167"'