# inventory.yml
all:
  children:
    fastapi:
      hosts:
        fastapi:
          ansible_host: 3.145.57.70
          ansible_user: ec2-user
    postgres:
      hosts:
        postgres:
          ansible_host: 10.0.29.1
          ansible_user: ec2-user
          ansible_ssh_common_args: '-o ProxyCommand="ssh -W %h:%p -q ec2-user@3.145.57.70"'